[package]
name = "TEST"
version = "0.1.0"
authors = ["AzenkChina <azenk1991@163.com>"]
edition = "2018"

[profile.dev]
debug = true
incremental = false

[profile.release]
debug = false
lto = true
incremental = false